### ISSUE TITLE
RequestError: Error:  getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by TimTerry73** [firebase/functions-samples#144]
**CODE:**

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const request = require('request-promise');

admin.initializeApp(functions.config().firebase);

exports.webhook = functions.database.ref('/users/{uid}/status').onWrite(event => {

      const status = event.data.val();

      return request({
        uri: 'http://website.com/page.php',
        method: 'POST',
        json: true,
        body: status,
        resolveWithFullResponse: true
      }).then(response => {
        if (response.statusCode >= 400) {
          throw new Error('HTTP Error: '+response.statusCode);
        }
        console.log('SUCCESS! Posted', response);
      });
});

**FIREBASE LOG ERROR**

RequestError: Error: getaddrinfo ENOTFOUND website.com website.com:80
    at new RequestError (/user_code/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/user_code/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/user_code/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/user_code/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by TimTerry73** [comment]
Come to find out i was getting this error ONLY because i was testing from a non-paid account.  Works on Blaze account.

**Comment by wi-cuckoo** [comment]
I just encounter the same problem of you. If you had figured it out? I have no any idea, just see a hint in one example:
```
TODO: Make sure you create your own Request Bin and change this URL to try this sample
```
