### ISSUE TITLE
Automatically moderating image function not working

### ISSUE THREAD

**Issue by rishabhcha** [firebase/functions-samples#174]
I'm getting this error:

```
ChildProcessError: Command failed: convert /tmp/test folder/yep.jpg -channel RGBA -blur 0x8 /tmp/test folder/yep.jpg
convert: unable to open image `/tmp/test': No such file or directory @ error/blob.c/OpenBlob/2712.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: unable to open image `folder/yep.jpg': No such file or directory @ error/blob.c/OpenBlob/2712.
convert: unable to open image `/tmp/test': No such file or directory @ error/blob.c/OpenBlob/2712.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `folder/yep.jpg' @ error/convert.c/ConvertImageCommand/3210.
 `convert /tmp/test folder/yep.jpg -channel RGBA -blur 0x8 /tmp/test folder/yep.jpg` (exited with error code 1)
    at callback (/user_code/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
at this line:
```
// Blur the image using ImageMagick.
   return exec(`convert ${tempLocalFile} -channel RGBA -blur 0x8 ${tempLocalFile}`);
```

**Comment by nicolasgarnier** [comment]
Looks like an issue with whitespace. I'll look into it.

**Comment by nicolasgarnier** [comment]
Probably need to do something like: 

```js
return exec(`convert "${tempLocalFile}" -channel RGBA -blur 0x8 "${tempLocalFile}"`);
```

**Comment by nicolasgarnier** [comment]
I'll probably switch from using `exec` to `spawn` like we do in the thumbnail sample: https://github.com/firebase/functions-samples/blob/master/quickstarts/thumbnails/functions/index.js#L80

**Comment by rishabhcha** [comment]
Yeah it was issue with spaces only and command :
`return exec(`convert "${tempLocalFile}" -channel RGBA -blur 0x8 "${tempLocalFile}"`);`
worked. Thanks.
