### ISSUE TITLE
Isomorphic React App example instructions don't work

### ISSUE THREAD

**Issue by davidwparker** [firebase/functions-samples#209]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
Example code fails to deploy:
https://github.com/firebase/functions-samples/tree/master/isomorphic-react-app

**Failing Function code used (including require/import commands at the top)**
```
firebase serve --only hosting, functions
```

**Steps to set up and reproduce**
Follow instructions on the example code, get to the `firebase serve` command.

### Debug output
```
firebase serve --only hosting,functions

=== Serving from '/Users/davidwparker/Dropbox/tech/react/firebases/functions-samples/isomorphic-react-app'...

i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
Warning: You're using Node.js v7.3.0 but Google Cloud Functions only supports v6.11.1.
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000

⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory. Please note that emulation of custom config values are not supported yet. Run firebase serve --only hosting to only serve hosting files.

FirebaseError: Error occurred while parsing your function triggers.

Error: functions.config() is not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (/Users/davidwparker/Dropbox/tech/react/firebases/functions-samples/isomorphic-react-app/functions/node_modules/firebase-functions/lib/config.js:46:19)
    at Object.config (/Users/davidwparker/Dropbox/tech/react/firebases/functions-samples/isomorphic-react-app/functions/node_modules/firebase-functions/lib/config.js:29:9)
    at Object.<anonymous> (/Users/davidwparker/Dropbox/tech/react/firebases/functions-samples/isomorphic-react-app/functions/index.js:28:29)
```

### Expected behavior

It should deploy locally ok

### Actual behavior

It doesn't serve / work

**Comment by davidwparker** [comment]
Scratch that- I redownloaded from scratch and everything is fine. Sorry.
