### ISSUE TITLE
Error: functions.config() is not available

### ISSUE THREAD

**Issue by valorloff** [firebase/functions-samples#214]
Hi!
big thank for this great sample!
i did `npm install` in all src, function and root of project, but
`sudo firebase serve --only hosting,functions`
```
FirebaseError: Error occurred while parsing your function triggers.

Error: functions.config() is not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (/home/valaoffice/functions-samples/isomorphic-react-app/functions/node_modules/firebase-functions/lib/config.js:46:19)
    at Object.config (/home/orloff/functions-samples/isomorphic-react-app/functions/node_modules/firebase-functions/lib/config.js:29:9)
    at Object.<anonymous> (/home/orloff/functions-samples/isomorphic-react-app/functions/index.js:28:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by laurenzlong** [comment]
What's your firebase-functions and firebase-tools versions respectively? And which sample are you talking about?

**Comment by valorloff** [comment]
sorry,
isomorphic-react-app, 
firebase-tools@3.9.2
@google-cloud/functions-emulator@1.0.0-alpha.23

**Comment by laurenzlong** [comment]
when you look in functions/package.json, what does the version number next to `firebase-functions` say?

**Comment by laurenzlong** [comment]
It needs to be at least v0.5.7 for config to be emulated properly. Filed https://github.com/firebase/functions-samples/issues/219 for the samples to be updated so they will work right away after cloning. 

In the meanwhile, you can run this command inside the functions folder:

`npm install --save firebase-functions@latest`

**Comment by valorloff** [comment]
Yes, after upgrade to
`"firebase-functions": "^0.6.2"`
it works properly!
Thanks!

**Comment by laurenzlong** [comment]
Thanks for the update!
