### ISSUE TITLE
Not able to deploy image-maker  Sample

### ISSUE THREAD

**Issue by syedsaadh** [firebase/functions-samples#225]
Hi, I am not able to deploy image-maker sample 

### How to reproduce these conditions
```
firebase deploy --only functions
```
**https://github.com/firebase/functions-samples/tree/master/image-maker**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

![image](https://user-images.githubusercontent.com/11473169/29829268-921f26f6-8cfc-11e7-925e-067e423e02c5.png)

**Comment by Fleker** [comment]
I just ran into this issue. Here's how I solved.

In my `package.json`, I replaced the dependency with
`"canvas-prebuilt": "1.*"`

**Comment by syedsaadh** [comment]
@Fleker thanks! 
Got Solved

**Comment by talltyler** [comment]
This is broken again with this error 
```
Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: libpng12.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```
Node-canvas has a different API with the 2.0 release. There might be a way to work around this by updating versions. Sorry I don't have time to dig in myself now.
