### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by ajaybeniwal** [firebase/functions-samples#252]
### How to reproduce these conditions
Create firebase function with functions.firestore.document('/messages/{documentId}')
**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output
TypeError: Cannot read property 'document' of undefined
    at Object.<anonymous> (/private/var/folders/h0/n48xhpys7gx3krtnwd3t518w02mj3p/T/fbfn_48543prnLWsx07lN4/index.js:50:44)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/ajasingh/.nvm/versions/node/v8.5.0/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
    at Object.<anonymous> (/Users/ajasingh/.nvm/versions/node/v8.5.0/lib/node_modules/firebase-tools/lib/triggerParser.js:32:3)
**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by kpolley** [comment]
I am getting the same error attempting to deploy from functions-samples/quickstarts/uppercase-firestore/

**Comment by kilombo** [comment]
Me too:

### How to reproduce these conditions
exports.usernameChanged = functions.firestore.document('/users/{userId}').onUpdate(event => {

### Debug output
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'document' of undefined
    at Object.<anonymous> (/private/var/folders/nw/yppj5c0x1_b2_x9cqld6ptrr0000gn/T/fbfn_130718HZ9Kn2sCicO/index.js:19:45)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:32:3)
