### ISSUE TITLE
Linkedin Auth Example fails on popup validation

### ISSUE THREAD

**Issue by stevewinni-cc** [firebase/functions-samples#316]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
Vanilla install of LinkedIn example script https://acf-framework.firebaseapp.com/

**Failing Function code used (including require/import commands at the top)**
When a user with the same email address exists in the system popup returns an error on;

ERROR 500 for resource;
https://us-central1-acf-framework.cloudfunctions.net/token?code=[the-code]&state=b756059fb917884aa05eff90d9927f8a47fa4c07&callback=tokenReceived net::ERR_ABORTED
(anonymous) @ popup.html?

**Steps to set up and reproduce**

Followed these steps here;

https://github.com/firebase/functions-samples/tree/master/linkedin-auth

**Sample data pasted or attached as JSON (not an image)**
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public"
  }
}

**Security rules used**
{
  "rules": {
    "linkedInAccessToken": {
      "$uid": {
        ".read": "auth.uid === $uid",
        ".write": "auth.uid === $uid"
      }
    }
  }
}

### Debug output

5:50:17.767 PM | warning | token | Error: The email address is already in use by another account.     at FirebaseAuthError.Error (native)     at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:25:28)     at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:90:23)     at Function.FirebaseAuthError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:114:16)     at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:350:45     at process._tickDomainCallback (internal/process/next_tick.js:135:7) | more_vert
-- | -- | -- | -- | --

5:50:17.765 PM | warning | token | Unhandled rejection
-- | -- | -- | --

**Screenshots**

### Expected behavior

Should inform the user that email already in use and with what mechanism

### Actual behavior

Popup. Blank screen with "Processing...." error in console.

**Comment by coluccini** [comment]
Same thing here ☝️

**Comment by jhuleatt** [comment]
LinkedIn retired its v1 OAuth APIs in 2019, breaking the underlying library used in this legacy 1st-gen sample.
