### ISSUE TITLE
Intermittent Failures when sending emails from cloud-functions, using node mailer and handlebars

### ISSUE THREAD

**Issue by rtman** [firebase/functions-samples#356]
Hi,
I've encountered an issue with sending html emails generated by handlebars through node mailer with cloud-functions. Though to be honest I'm not exactly sure where to post this issue since I don't really know the cause of the issue yet, but it is based in cloud functions so I will start here I guess.

Intermittently my emails will fail to send with the following error:

```
Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:229:31)
    at step (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
### How to reproduce these conditions
```

I've tested this about 25 times, with 3 variances on the same function in my index.js:

1. No_readHTMLFile - Basic HTML info is inside a variable in the function
2. readHTMLFile - Basic HTML info is read from a file.
3. Original Function in my App - More Complex HTML info is read from a file.

As far as I can tell this behavior only occurs with 2 and 3 and then only about half the time. So it seems that it is specifically when the contents of an html file is read using `file`, to use in the handlebars engine.

I think this isn't specifically a nodemailer issue, or handlebars issue but reading of an html file? I don't understand why it throws a credentials error though.

**Failing Function code used (including require/import commands at the top)**

I've omitted my original function and put in 1 and 2 from above, since they are more simple.
```
//setup
const functions = require('firebase-functions');
const nodemailer = require('nodemailer');
const handlebars = require('handlebars');
const file = require('file-system');
var admin = require("firebase-admin");
var serviceAccount = require("./service-account-credentials.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "your database"
});
const gmailEmail = functions.config().gmail.email;
const gmailPassword = functions.config().gmail.password;
const mailTransport = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: gmailEmail,
    pass: gmailPassword
  }
});
const APP_NAME = 'your App Name'; 


//email functions
function sendNewOrderEmail_NOreadHTMLFile() {
  const mailOptions = {
    from: `${APP_NAME} <noreply@google.com>`,
    //testing, email is hardcoded for now to test emails
    to: `email@google.com`
  };

  mailOptions.subject = `NOreadHTMLFile ${APP_NAME}!`;
  const html = "<html>\
<head>\
<title>EXAMPLE</title>\
</head>\
<body>\
<table>\
<tr>\
<td>TEST</td>\
</tr>\
</table>\
</body>\
</html>"
  const template = handlebars.compile(html);
  const htmlToSend = template();    
  mailOptions.html = htmlToSend;
  mailTransport.sendMail(mailOptions, console.log('New Order email sent to:', mailOptions.to))
  return true
}

exports.NO_readHTMLFile = functions.firestore.document("orders/{docId}").onCreate(event => {
  return sendNewOrderEmail_NOreadHTMLFile();
});



//email functions
function sendNewOrderEmail_readHTMLFile() {
  const mailOptions = {
    from: `${APP_NAME} <noreply@google.com>`,
    //testing, email is hardcoded for now to test emails
    to: `email@google.com`
  };

  mailOptions.subject = `readHTMLFile ${APP_NAME}!`;

  const readHTMLFile = function(path, callback) {
      file.readFile(path, {encoding: 'utf-8'}, function (err, html) {
          if (err) {
              throw err;
              callback('readHTMLFile Error', err);
          }
          else {
              callback(null, html);
          }
      });
  };

  readHTMLFile('./emailTemplates/test.html', (err, html) => {
    const template = handlebars.compile(html);
    const htmlToSend = template();    
    mailOptions.html = htmlToSend;
    mailTransport.sendMail(mailOptions, console.log('New Order email sent to:', mailOptions.to))
  });
  return true
}

exports.readHTMLFile = functions.firestore.document("orders/{docId}").onCreate(event => {
  return sendNewOrderEmail_readHTMLFile();
});
```
test.html
```
<html>
<head>
<title>EXAMPLE</title>
</head>
<body>
<table>
<tr>
<td>
TEST
</td>
</tr>
</table>
</body>
</html>
```
package.json
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "@google-cloud/storage": "^1.5.1",
    "algoliasearch": "^3.24.5",
    "child-process-promise": "^2.2.1",
    "file-system": "^2.2.2",
    "firebase-admin": "^5.11.0",
    "firebase-functions": "^0.8.2",
    "handlebars": "^4.0.11",
    "i": "^0.3.6",
    "mkdirp": "^0.5.1",
    "mkdirp-promise": "^5.0.1",
    "nodemailer": "^4.4.1",
    "npm": "^5.6.0"
  },
  "private": true
}
```

**Steps to set up and reproduce**

Setup a functions directory as normal, install node mailer and handlebars and load the functions above.

**Sample data pasted or attached as JSON (not an image)**

N/A

**Security rules used**

```
service cloud.firestore {
  match /databases/{database}/documents {
    // All Collections
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

The link above doesn't show anything relating these functions. I will post an image of the logs on these functions below.

![sendorderemail](https://user-images.githubusercontent.com/20849135/38246057-c59c7152-3740-11e8-8a7c-8694662453d7.PNG)

### Expected behavior

The function should send a email when a new order is placed

### Actual behavior

It intermittently fails to send emails (around half the time) with the credentials error stated above.

**Comment by rtman** [comment]
As a fix I'm just declaring my entire html template as a variable in my function, so far no failures.

**Comment by nicolasgarnier** [comment]
Very strange. I would guess this might be due to flakyness in the service rather than an issue with your code.
