### ISSUE TITLE
delete-unused-accounts-cron : TypeError: functions.https.onRequest(...).then is not a function

### ISSUE THREAD

**Issue by filol** [firebase/functions-samples#359]
### How to reproduce these conditions

Follow the readme : 

- Create a Firebase Project using the Firebase Developer Console
- Download this sample e.g. git clone https://github.com/firebase/functions-samples
- Enter the sample directory cd functions-samples/delete-unused-accounts-cron
- Setup the sample with your project firebase use --add and follow the instructions.
- Install node dependencies of your Functions cd functions; npm install; cd -
- Deploy your project using firebase deploy.

### Debug output

```firebase deploy

=== Deploying to 'project'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: functions.https.onRequest(...).then is not a function
    at Object.<anonymous> (functions-samples\delete-unused-accounts-cron\functions\index.js:47:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:18:11
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:38:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3```

**Comment by nicolasgarnier** [comment]
Thanks for the heads up! An error due to a refactoring slipped through. Should be Fixed now :)

**Comment by filol** [comment]
You need to add `});` to line 70 ;)
After that it's fixed

**Comment by filol** [comment]
Hum the function doesn't work.... When i launch, after few second, i got this error : 
```ReferenceError: userToDelete is not defined
    at getUsers.then.then.catch (/user_code/index.js:67:56)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/user_code/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)```

I need to open a new issue?

**Comment by nicolasgarnier** [comment]
OK it looks like the refactoring had completely broken the sample. I switched back to a previous version of the code. Can you please have another look? :)

**Comment by filol** [comment]
It's working ! :) but on some users (~25%) i get this error : 
```
Deletion of inactive user account wLx9W0KVJ5WchWRzjC5TqVS3sc63 failed: { Error: There is no user record corresponding to the provided identifier.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:143:16)
    at Function.FirebaseAuthError.fromServerError (/user_code/node_modules/firebase-admin/lib/utils/error.js:173:16)
    at /user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:680:45
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'auth/user-not-found',
     message: 'There is no user record corresponding to the provided identifier.' },
  codePrefix: 'auth' }

**Comment by nicolasgarnier** [comment]
Damned! :)

I'm wondering if this could be that we try to delete the same account twice (so this will fail with this error on the second attempt). Can you check that the account with UID `wLx9W0KVJ5WchWRzjC5TqVS3sc63 ` actually exists or still exists?

**Comment by nicolasgarnier** [comment]
By the way can you also try this new code that I sent out:

https://github.com/firebase/functions-samples/pull/362

You can get it by using the code in the branch  `delete-unused-accounts-cron-listUsers`. It's using a new way to list users and the code is a lot simpler.

**Comment by filol** [comment]
Unfortunately, it still exists ...
With the code in the new branch i get this error : 
```
ReferenceError: getUsers is not defined
    at exports.accountcleanup.functions.https.onRequest (/user_code/index.js:46:10)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:37:41)
    at /var/tmp/worker/worker.js:676:7
    at /var/tmp/worker/worker.js:660:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by nicolasgarnier** [comment]
Damn, sorry about that. This is now fixed :)

**Comment by filol** [comment]
Hum you forget another ;) 
```
ReferenceError: getUsers is not defined
    at admin.auth.listUsers.then (/user_code/index.js:90:14)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by nicolasgarnier** [comment]
😅 done. I hope that's it 😄

**Comment by filol** [comment]
Other one ! :') 
``` 
ReferenceError: userIds is not defined
    at admin.auth.listUsers.then (/user_code/index.js:93:12)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by filol** [comment]
You can't test your code before push ?

```
Deletion of inactive user account undefined failed: { Error: The uid must be a non-empty string with at most 128 characters.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:143:16)
    at FirebaseAuthRequestHandler.deleteAccount (/user_code/node_modules/firebase-admin/lib/auth/auth-api-request.js:479:35)
    at Auth.deleteUser (/user_code/node_modules/firebase-admin/lib/auth/auth.js:253:40)
    at deleteInactiveUser (/user_code/index.js:65:25)
    at PromisePool (/user_code/index.js:48:47)
    at Object.next (/user_code/node_modules/es6-promise-pool/es6-promise-pool.js:52:23)
    at PromisePool._proceed (/user_code/node_modules/es6-promise-pool/es6-promise-pool.js:200:37)
    at PromisePool._onPooledPromiseFulfilled (/user_code/node_modules/es6-promise-pool/es6-promise-pool.js:169:12)
    at /user_code/node_modules/es6-promise-pool/es6-promise-pool.js:188:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'auth/invalid-uid',
     message: 'The uid must be a non-empty string with at most 128 characters.' },
  codePrefix: 'auth' }

**Comment by nicolasgarnier** [comment]
I was using the GitHub online editor as I was on the go and thought the changes were simple enough (obviously that was a bad idea). I'll be able to to test this soon.

I just pushed this fix (still untested) I can test in a couple hours but if you want to try go ahead (we should be getting there :)

btw when you see something you could fix feel free to send a Pull Request. You can simply click on the edit icon in GitHub to quickly create a PR: 
![image](https://user-images.githubusercontent.com/3766663/38405099-67174cc6-396e-11e8-843d-26bf601c2b84.png)

:)
