### ISSUE TITLE
firebase cloud functions children limit example

### ISSUE THREAD

**Issue by dishak** [firebase/functions-samples#361]
```
'use strict';
const functions = require('firebase-functions');
// Max number of lines of the chat history.
const MAX_LOG_COUNT = 1;
// Removes siblings of the node that element that triggered the function if there are more than MAX_LOG_COUNT.
// In this example we'll keep the max number of chat message history to MAX_LOG_COUNT.
exports.truncate = functions.database.ref('/chat/{pushId}').onWrite((change) => {
  const parentRef = change.after.ref.parent;
  return parentRef.once('value').then((snapshot) => {
    if (snapshot.numChildren() >= MAX_LOG_COUNT) {
      let childCount = 0;
      const updates = {};
      snapshot.forEach((child) => {
        if (++childCount <= snapshot.numChildren() - MAX_LOG_COUNT) {
          updates[child.key] = null;
        }
      });
      // Update the parent. This effectively removes the extra children.
      return parentRef.update(updates);
    }
    return null;
  });
});

```
here {pushId} which is random key I want to limit. This code I got from here [https://github.com/firebase/functions-samples/blob/master/limit-children/functions/index.js](url)

I exactly deployed same code with same child nodes still the error in logs was:
```
TypeError: Cannot read property 'ref' of undefined
    at exports.truncate.functions.database.ref.onWrite (/user_code/index.js:11:33)
    at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:59:27)
    at next (native)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71
    at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)
    at /var/tmp/worker/worker.js:700:26
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by nicolasgarnier** [comment]
Are you using the latest version of the `firebase-functions` package? For this code to work you'll need v 1.0.0 since there has been breaking changes (we released this 2 days ago).  Make sure you are not using any versions 0.x.x

**Comment by dishak** [comment]
@nicolasgarnier  ya thankk you worked for me.
I am facing another issue with google sheet sync example.

issue posted 

https://github.com/firebase/functions-samples/issues/364
