### ISSUE TITLE
Email quickstart resulting in error 534-5.7.14

### ISSUE THREAD

**Issue by markgoho** [firebase/functions-samples#39]
Turned on Google auth, deployed app: https://functionstest-c1518.firebaseapp.com/

When logging in, I get the following error in the Function log:

```
Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs7
534-5.7.14 UF7mumzUwFIZrMDWiiimSdrlEvZIp8kRC3QRkzqwfOM94wkvVFys_Yjllj6KGuBubi6SwF
534-5.7.14 BDIHCpQgETRmmgkyJXfYN4Ne3uG3tnsVJk7oGR4Z5fvgeIkuOJOKkvRA8cLWFN67ya4r28
534-5.7.14 u-eBDds9bTTh1poYtxXWk1x80iaSn_2VlJHWJnB0Yql6r_-A2lDE8nt00lWP7eoUpkzVih
534-5.7.14 x1DeI0bGyNqNHRRUuucw0k95Ph-CY> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 100sm8943270iot.39 - gsmtp
    at SMTPConnection._formatError (/user_code/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._actionAUTHComplete (/user_code/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:1231:30)
    at SMTPConnection.<anonymous> (/user_code/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:319:22)
    at SMTPConnection._processResponse (/user_code/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData (/user_code/node_modules/nodemailer/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
```

**Comment by markgoho** [comment]
From the [support article](https://support.google.com/mail/answer/78754) in the error code, I enabled access for less secure apps here: https://www.google.com/settings/security/lesssecureapps and also allowed access to DisplayUnlockCaptcha here: https://accounts.google.com/DisplayUnlockCaptcha

Welcome and Bye emails are both working now!

**Comment by markgoho** [comment]
Perhaps the docs could be updated to reflect these two (probably) required steps.

**Comment by nicolasgarnier** [comment]
Thanks @markgoho. You are probably right, I'll add these steps. Were you using a gmail account? Or a GSuite account?

**Comment by markgoho** [comment]
@nicolasgarnier gmail account to send the emails.

**Comment by agersoncgps** [comment]
I am 100% sure I am using the correct password (I tried a GSuite account and a regular gmail account) and I have enabled less secure apps and authorized the captcha. Still getting: There was an error while sending the email: { Error: Invalid login: 535-5.7.8 Username and Password not accepted.

**Comment by dave-k** [comment]
@carlosdelamora 
I have also enabled both 1. & 2. 
After a few hours I start getting an error: "Error: Invalid login: 534-5.7.14" 
After Enabling 2. again, gmail login is successful.

Did you resolve the issue with enabling [https://accounts.google.com/DisplayUnlockCaptcha](url) again?
