### ISSUE TITLE
Write from firebase realtimedb to spreadsheet

### ISSUE THREAD

**Issue by ABenn17282002** [firebase/functions-samples#391]
### How to reproduce these conditions

I am trying to write from the firebase to the spreadsheet. However, it stops when writing to the spreadsheet.

**Sample name or URL where you found the bug**

https://github.com/firebase/functions-samples/tree/master/google-sheet-sync

**Failing Function code used (including require/import commands at the top)**

appendrecordtospreadsheet

**Steps to set up and reproduce**

Follow the instructions in functions-samples / google-sheet-sync/README.md

**Sample data pasted or attached as JSON (not an image)**
```
{
  "name": "google-sheet-sync",
  "description": "Syncs new Firebase data to a Google Sheet",
  "dependencies": {
    "firebase-admin": "^5.10.0",
    "firebase-functions": "^1.0.0",
    "google-auth-library": "^1.3.1",
    "googleapis": "^27.0.0"
  },
  "devDependencies": {
    "eslint": "^4.13.1",
    "eslint-plugin-promise": "^3.6.0"
  },
  "scripts": {
    "lint": "./node_modules/.bin/eslint --max-warnings=0 .",
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "private": true
}
```
**Security rules used**
```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```
### Debug output

![firebasescreenshot](https://user-images.githubusercontent.com/25114999/39610016-477b60ca-4f88-11e8-8f30-64d18b4a9f8f.png)

### Expected behavior

Write to spreadsheet from firebase realtimeDB

### Actual behavior

Although writing to firebase is possible, writing to the spreadsheet is a situation where the following error can not be issued. Please help me.
-------------------------------------------------------------------- ------------------------
Function load error: Code in file index.js can not be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: OAuth2Client is not a constructor
???? at Object. <anonymous> (/user_code/index.js:45:30)
-------------------------------------------------------------------- --------------------------

**Comment by prescottprue** [comment]
Things were working for me until I updated to a newer version of `googleapis` (which seem to not work the same) then I started to see a similar error. Pointing to `^22.*.*` in my package file got things working again with sample code, but not sure it is the same issue.

**Comment by ABenn17282002** [comment]
Sorry for your frequent inquiries.
The following error appears in the function. 
-----------------------------------------------------------------------------------------------------------------
appendrecordtospreadsheet
TypeError: Cannot read property 'access_token' of null
    at OAuth2Client.<anonymous> (/user_code/node_modules/google-auth-library/build/src/auth/oauth2client.js:335:39)

authgoogleapi
OAuth2Client { domain: null, _events: {}, _eventsCount: 0, _maxListeners: undefined,.....
-----------------------------------------------------------------------------------------------------------------
Do you need the procedure of the URL below? I hope to tell you
https://firebase.google.com/docs/web/setup?authuser=0

If there is another effective method, I would like to tell you

**Comment by ABenn17282002** [comment]
When deploying with the following code, you get an error "Error: No access, refresh token or API key is set."

```
'use strict';

// Sample trigger function that copies new Firebase data to a Google Sheet

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const {OAuth2Client} = require('google-auth-library');
const {google} = require('googleapis');

// TODO: Use firebase functions:config:set to configure your googleapi object:
// googleapi.client_id = Google API client ID,
// googleapi.client_secret = client secret, and
// googleapi.sheet_id = Google Sheet id (long string in middle of sheet URL)
const CONFIG_CLIENT_ID = functions.config().googleapi.client_id;
const CONFIG_CLIENT_SECRET = functions.config().googleapi.client_secret;
const CONFIG_SHEET_ID = functions.config().googleapi.sheet_id;

// TODO: Use firebase functions:config:set to configure your watchedpaths object:
// watchedpaths.data_path = Firebase path for data to be synced to Google Sheet
const CONFIG_DATA_PATH = functions.config().watchedpaths.data_path;

// The OAuth Callback Redirect.
const FUNCTIONS_REDIRECT = `https://${process.env.GCLOUD_PROJECT}.firebaseapp.com/oauthcallback`;

// setup for authGoogleAPI
const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];
const functionsOauthClient = new OAuth2Client(CONFIG_CLIENT_ID, CONFIG_CLIENT_SECRET,
  FUNCTIONS_REDIRECT);

// OAuth token cached locally.
let oauthTokens='/.credentials/';


// visit the URL for this Function to request tokens
exports.authgoogleapi = functions.https.onRequest((req, res) => {
  res.set('Cache-Control', 'private, max-age=0, s-maxage=0');
  res.redirect(functionsOauthClient.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
    prompt: 'consent',
  }));
});

// setup for OauthCallback
const DB_TOKEN_PATH = '/api_tokens';


// after you grant access, you will be redirected to the URL for this Function
// this Function stores the tokens to your Firebase database
exports.oauthcallback = functions.https.onRequest((req, res) => {
  res.set('Cache-Control', 'private, max-age=0, s-maxage=0');
  const {tokens} ={ "access_token": "aaaaa", "refresh_token": "bbbbbb" };
  const code = req.query.code;
  functionsOauthClient.getToken(code, (err, tokens) => {
    if (err) {
      return res.status(400).send(err);
    }
    return admin.database().ref(DB_TOKEN_PATH).set(tokens)
        .then(() => {
          return res.status(200).send('App successfully configured with new Credentials. '
            + 'You can now close this page.');
        });
  });
});

// trigger function to write to Sheet when new data comes in on CONFIG_DATA_PATH
exports.appendrecordtospreadsheet = functions.database.ref(`${CONFIG_DATA_PATH}/{ITEM}`).onCreate(
    (snap) => {
      const newRecord = snap.val();
      return appendPromise({
        spreadsheetId: CONFIG_SHEET_ID,
        range: 'A:C',
        valueInputOption: 'USER_ENTERED',
        insertDataOption: 'INSERT_ROWS',
        resource: {
          values: [[newRecord.firstColumn, newRecord.secondColumn, newRecord.thirdColumn]],
        },
      });
    });

// accepts an append request, returns a Promise to append it, enriching it with auth
function appendPromise(requestWithoutAuth) {
  return new Promise((resolve, reject) => {
    return getAuthorizedClient().then((client) => {
      const sheets = google.sheets('v4');
      const request = requestWithoutAuth;
      request.auth = client;
      return sheets.spreadsheets.values.append(request, (err, response) => {
        if (err) {
          console.log(`The API returned an error: ${err}`);
          return reject(err);
        }
        return resolve(response.data);
      });
    });
  });
}

// checks if oauthTokens have been loaded into memory, and if not, retrieves them
function getAuthorizedClient() {
  if (oauthTokens) {
    return Promise.resolve(functionsOauthClient);
  }
  return admin.database().ref(DB_TOKEN_PATH).once('value').then((snapshot) => {
    oauthTokens = snapshot.val();
    functionsOauthClient.setCredentials(oauthTokens);
    return functionsOauthClient;
  });
}

// HTTPS function to write new data to CONFIG_DATA_PATH, for testing
exports.testsheetwrite = functions.https.onRequest((req, res) => {
  const random1 = Math.floor(Math.random() * 100);
  const random2 = Math.floor(Math.random() * 100);
  const random3 = Math.floor(Math.random() * 100);
  const ID = new Date().getUTCMilliseconds();
  return admin.database().ref(`${CONFIG_DATA_PATH}/${ID}`).set({
    firstColumn: random1,
    secondColumn: random2,
    thirdColumn: random3,
  }).then(() => res.status(200).send(
    `Wrote ${random1}, ${random2}, ${random3} to DB, trigger should now update Sheet.`));
});

```
● About the part of let oauthTokens = null ;, there is / / OAuth token cached locally.
Let oauthTokens = '/. credentials /'; Is the code correct?

● // Now tokens contains an access_token and an optional refresh_token. Save them.
Although it is the above part, where should I define access_token and an optional refresh_token? please tell me
