### ISSUE TITLE
ApiError: Not Found  at Object.parseHttpRespBody@google-cloud/storage/

### ISSUE THREAD

**Issue by steelx** [firebase/functions-samples#398]
`ApiError: Not Found
    at Object.parseHttpRespBody (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js`

### How to reproduce these conditions
When I make a POST request to : `https://us-central1-<PROJECT_ID>.cloudfunctions.net/listFiles`
with post data {"uid": "SOME_LONG_STRING"}

### I get following error in postman
```
{"code":404,"errors":[{"domain":"global","reason":"notFound","message":"Not Found"}],"message":"Not Found"}
```

### Firebase LOG:
<img width="1046" alt="screen shot 2018-05-13 at 7 28 29 pm" src="https://user-images.githubusercontent.com/3184210/39968018-e8f7008c-56e3-11e8-8afb-85a24f28dcef.png">

{ ApiError: Not Found
    at Object.parseHttpRespBody (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:199:30)
    at Object.handleResp (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:137:18)
    at /user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:502:12
    at Request.onResponse [as _callback] (/user_code/node_modules/@google-cloud/storage/node_modules/retry-request/index.js:195:7)
    at Request.self.callback (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: 404,
  errors: [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ],
  response: undefined,
  message: 'Not Found' }

## FUNCTIONS code
[code](https://gist.github.com/steelx/ba31b18f090faa10a6a135804539b80f.js)

https://gist.github.com/steelx/ba31b18f090faa10a6a135804539b80f.js

**Comment by nickbae91** [comment]
Also facing this issue... have you been able to figure this out yet?

**Comment by Donmclean** [comment]
I'm getting the same error also...
