### ISSUE TITLE
I'm getting an error: ChildProcessError

### ISSUE THREAD

**Issue by bakbuz** [firebase/functions-samples#434]
How can i fix this problem. 

`ChildProcessError: `convert /tmp/188b775e-8611-4e99-adb8-7956e6d71896.png -thumbnail 200x200> /tmp/thumb_188b775e-8611-4e99-adb8-7956e6d71896.png` failed with code 1
    at ChildProcess.<anonymous> (/user_code/node_modules/child-process-promise/lib/index.js:132:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)`

**Comment by abdulwahabone** [comment]
Same issue with me, did u manage to solve it.

**Comment by bakbuz** [comment]
@abdulwahabone No, I did not.

**Comment by bakbuz** [comment]
@abdulwahabone  there is a solution here.

https://stackoverflow.com/questions/44479085/childprocesserror-for-image-moderation-firebase-function
