### ISSUE TITLE
"ReferenceError: admin is not defined" on generateThumbnail

### ISSUE THREAD

**Issue by bravotan** [firebase/functions-samples#485]
I deployed the generateThumbnail function, and uploaded the image file to Firebase Storage, but the following error was output.

```
ReferenceError: admin is not defined
    at exports.generateThumbnail.functions.storage.object.onFinalize (/srv/index.js:57:18)
    at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at /worker/worker.js:731:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7
```

**Comment by samtstern** [comment]
Looks like this was fixed by #486
