### ISSUE TITLE
generate-thumbnail sample: ImageMagick functionality unavailable ENOENT

### ISSUE THREAD

**Issue by NimaiMalle** [firebase/functions-samples#501]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
generate-thumbnail

**Failing Function code used (including require/import commands at the top)**
```
const spawn = require('child-process-promise').spawn;
...
await spawn('convert', [tempLocalFile, '-thumbnail', `${THUMB_MAX_WIDTH}x${THUMB_MAX_HEIGHT}>`, tempLocalThumbFile], {capture: ['stdout', 'stderr']});
```

**Steps to set up and reproduce**
Follow the steps in the README for setting up your own instance of the generate-thumbnail project.
Upload an image to the project's Storage
View the logs

**Security rules used**
Default rules for Storage
IAM:
```
imagemagick-xxxxxx@appspot.gserviceaccount.com
   App Engine default service account
   Service Account Token Creator
   Storage Object Admin
```

### Debug output

```
Error: spawn convert ENOENT
     at _errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
     at onErrorNT (internal/child_process.js:372:16)
     at _combinedTickCallback (internal/process/next_tick.js:138:11)
     at process._tickDomainCallback (internal/process/next_tick.js:218:9) |  
```

### Expected behavior
ImageMagick `convert` program spawns successfully and resizes the image according to supplied arguments

### Actual behavior
Child process spawn fails, not finding the `convert` program, resulting in the error `spawn convert ENOENT`

#### Try spawning identify
Tests with other ImageMagick executables also fail, for example, calling `identify` results in `spawn identify ENOENT`.

#### Use dpkg to see if ImageMagick is installed
Using spawn to run `dpkg` results in:
```
dpkg -L imagemagick
dpkg-query: package 'imagemagick' is not installed
```
#### Inspect the $PATH
Using `ls` and `grep` to look for *convert* in all directories in the $PATH finds nothing.

**Comment by Cdik** [comment]
I have the same issue. Thanks @NimaiMalle for reporting.

As we discussed on Firebase Slack channel, I would like to add that there's no consistency after each `deploy` command. 

You `deploy`, it works. Then you `deploy` again and it breaks. Etc, etc...

Don't know if it's relevant but it _could eventually_ come from the `deploy` command ...

**Comment by rodrigomata** [comment]
Have you tried upgrading your CLI to the latest version and deploy again?

**Comment by NimaiMalle** [comment]
@rodrigomata I had updated a week or so ago, but just did now:
$ firebase --version
6.0.0

Re-deployed.  Same result, though.  I notice when I use `exec` to run "convert", I get a different error:
"/bin/sh: 1: convert: not found"

**Comment by Cdik** [comment]
After spending a day trying to debug this sh*t I discovered something really nasty. :triumph:

If you try using IM or GM with temporary files saved in your bucket using `admin.storage().bucket("myBucket")`, you will randomly get a `ENOENT` or other `exit code 1` , `command failed` etc.... because, as written in this specific documentation ([see here](https://firebase.google.com/docs/functions/gcp-storage-events#download_transform_and_upload_a_file)), in between lot of different things:
>Use gcs.bucket.file(filePath).download to download a file to a temporary directory on your Cloud Functions instance. In this location, you can process the file as needed and then upload to Cloud Storage.

Which means that, otherwise, the file is saved in..... I don’t know where but not accessible.

The annoying part of this is that there are 3 or 4 (or maybe more) different documentations regarding the download/upload/IM processes and none of them are saying the same sh*t! 😑 
Anyway :slightly_smiling_face: , IM/GM are working perfectly again if I stick to `gcs.bucket` methods.
Hope it will help you. :wave:

**Comment by Cdik** [comment]
My previous comment is maybe not clear enough...

Not working:
>const bucket = admin.storage().bucket("MyBucket");
>const file = bucket.file(filePath);
>const tempLocalFile = path.join(os.tmpdir(), fileName);
>file.download({destination: tempLocalFile}, callback)};

Working:
>const bucket = gcs.bucket("MyBucket");
>const tempFilePath = path.join(os.tmpdir(), fileName);
>bucket.file(filePath).download({destination: tempFilePath});

**Comment by Cdik** [comment]
If anyone has a clear explanation on why the two different initialisations of the bucket make IM/GM works or not, ✋ let me know.
`admin.storage().bucket("myBucket")`
vs
`gcs.bucket("myBucket")`

**Comment by NimaiMalle** [comment]
@Cdik Hey, I feel your pain, but you should file a separate support ticket or github issue for your storage bucket behavior.  I totally understand that you've got an issue here!  But it will reduce the team's ability to triage and respond if we add multiple issues under one ticket.  Please stick to additional information related to launching ImageMagick tools within Firebase Cloud Functions on this thread.

FYI - support did have me try deleting the function that used `convert` and then re-deploying it, and while anecdotal, it did start working for me after that.

**Comment by jhuleatt** [comment]
We replaced the ImageMagick sample with [`Node/quickstarts/thumbnails`](https://github.com/firebase/functions-samples/tree/main/Node/quickstarts/thumbnails) and [`Python/thumbnails`](https://github.com/firebase/functions-samples/tree/main/Python/thumbnails). The Node sample processes images in-process with `sharp`, removing any dependence on system ImageMagick binaries. Closing as completed.
