### ISSUE TITLE
TypeError: Cannot read property 'customer_id' of undefined

### ISSUE THREAD

**Issue by willvlad** [firebase/functions-samples#507]
Deployed as per the example. But keep on getting these errors from calling the functions from index.html:

createStripeCharge
```
TypeError: Cannot read property 'customer_id' of undefined
    at exports.createStripeCharge.functions.firestore.document.onCreate (/srv/index.js:35:34)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

addPaymentSource
```
TypeError: Cannot read property 'customer_id' of undefined
    at exports.addPaymentSource.functions.firestore.document.onCreate (/srv/index.js:73:38)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
To exclude any rules issues, I've allowed read and write firestore.rules to anyone with uid.

Any idea what could be causing these errors?

**Comment by willvlad** [comment]
Thanks @alemens ! So it looks like the example code is not good anymore. Could it be because of the awaits that seem to be highlighted by jshint on my ide (code)?

Have you changed the other functions within the file as well? If so, would you mind posting them as well, many thanks!!

**Comment by warrenhharding** [comment]
Any update on this particular problem? I'm experiencing it at the moment and can't find a way around it. Thanks.
