### ISSUE TITLE
isomorphic-example doesn't work

### ISSUE THREAD

**Issue by salmazov** [firebase/functions-samples#512]
`functions-samples/isomorphic-react-app (Node-8) $ firebase deploy

=== Deploying to 'isomorphic-82f19'...

i  deploying database, functions, hosting
i  database: checking rules syntax...
✔  database: rules syntax for database isomorphic-82f19 is valid
i  functions: ensuring necessary APIs are enabled...
⚠  functions: missing necessary APIs. Enabling now...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

/home/ubuntu/workspace/ssr/functions-samples/isomorphic-react-app/functions/index.js:41
app.get('/:userId?', async (req, res) => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15`

**Comment by mbleigh** [comment]
You'll need to upgrade your local version of node.js to 8 or higher

**Comment by samtstern** [comment]
Thanks @mbleigh !
