### ISSUE TITLE
SyntaxError: Unexpected token ( in generateMonoAudio example

### ISSUE THREAD

**Issue by LiamInJapan** [firebase/functions-samples#521]
### How to reproduce these conditions

1) copy code from sample and deploy

- https://github.com/firebase/functions-samples/tree/Node-8/ffmpeg-convert-audio

- firebase deploy --only functions

Get error on deployment:

i  functions: updating Node.js 6 function generateMonoAudio(us-central1)...
⚠  functions[generateMonoAudio(us-central1)]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/index.js:37
exports.generateMonoAudio = functions.storage.object().onFinalize(async (object) => {
                                                                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:423:24)

Functions deploy had errors with the following functions:
	generateMonoAudio

It would seem it doesn't like the async and await keyword combination?

**Comment by binloan** [comment]
Are you sure node v8 is specified in your `package.json`? Node v6 which is default for Firebase does not support the async feature.
