### ISSUE TITLE
TypeError: Data must be a string or a buffer at Hmac.update in github-to-slack example

### ISSUE THREAD

**Issue by eysi09** [firebase/functions-samples#533]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
[github-to-slack](https://github.com/firebase/functions-samples/tree/Node-8/github-to-slack)

**Failing Function code used (including require/import commands at the top)**
```javascript
// imports
const functions = require('firebase-functions');
const rp = require('request-promise');
const crypto = require('crypto');
const secureCompare = require('secure-compare');

// Failing function code
  const hmac = crypto.createHmac(cipher, functions.config().github.secret)
      .update(req.body)
      .digest('hex');
```
**Steps to set up and reproduce**

I followed the steps in the README for the `github-to-slack` example and noticed the issue when testing the project by triggering Github events.

The problem is in this function:

```javascript
  const hmac = crypto.createHmac(cipher, functions.config().github.secret)
      .update(req.body)
      .digest('hex');
```
The `update` function only accepts a string or a buffer as the first parameter, not a JSON object like `req.body`. 

**Sample data pasted or attached as JSON (not an image)**

N/A

**Security rules used**

N/A

### Debug output

```
TypeError: Data must be a string or a buffer at Hmac.update (crypto.js:99:16) at exports.githubWebhook.functions.https.onRequest (/srv/index.js:33:8) at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:57:9) at /worker/worker.js:726:7 at /worker/worker.js:709:11 at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickDomainCallback (internal/process/next_tick.js:219:9)
--
```

### Expected behavior

The `update` function should receive a string parameter and the `hmac` assignment should not fail.

### Actual behavior

The `update` function should receives a JSON object parameterand  the `hmac` assignment fails.

**Comment by eysi09** [comment]
I'd be happy to submit a PR for this when I time over the weekend.
