### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by tcaer** [firebase/functions-samples#535]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
Stripe nodejs library.

**Failing Function code used (including require/import commands at the top)**
This error occurs when creating a user. 
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

const stripe = require('stripe')(functions.config().stripe.testkey);

exports.createStripeCustomer = functions.auth.user().onCreate((user, context) => {
    return stripe.customers.create({
        email: user.email
    })
        .then(customer => {
            const updates = {};
            updates[`/customers/${customer.id}`] = user.uid;
            updates[`/users/${user.uid}/customerId`] = customer.id;

            return admin.database().ref().update(updates);
        });
});
```

**Steps to set up and reproduce**

The project is pretty similar to the one here. I have Vue 2 frontend which runs `firebase.auth().createUserWithEmailAndPassword` to create users.

### Debug output
```
TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:359:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:206:15)
    at makeRequest (/user_code/node_modules/stripe/lib/StripeResource.js:275:9)
    at /user_code/node_modules/stripe/lib/StripeResource.js:264:7
    at /user_code/node_modules/stripe/lib/stripe.js:204:7
    at /user_code/node_modules/stripe/lib/stripe.js:226:7
    at ChildProcess.exithandler (child_process.js:190:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
```

### Expected behavior
A database document should be created with the value of the customer's ID.

### Actual behavior
Stripe throws an error saying that is has headers with invalid characters.

**Comment by tcaer** [comment]
It turns out that when copying my API key from stripe, a newline character was added at the front. Simply reentering the key properly fixed all of my issues.
