### ISSUE TITLE
Confirmation Email error

### ISSUE THREAD

**Issue by hbgxsm95** [firebase/functions-samples#549]
### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

TypeError: snapshot.changed is not a function
    at exports.sendEmailConfirmation.functions.database.ref.onWrite (/srv/index.js:38:17)
    at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at /worker/worker.js:804:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Screenshots**

**Comment by cyiboy** [comment]
having the same problem, really need help

**Comment by bgashler1** [comment]
This example doesn't work for me on the latest API. Looking at the docs, `change` method doesn't appear to be in the [current API for snapshots](https://firebase.google.com/docs/reference/functions/providers_database_.datasnapshot.html#exists).
