### ISSUE TITLE
 TypeError: Cannot read property 'app_shared_secret' of undefined while firebase deploy

### ISSUE THREAD

**Issue by tiger1947** [firebase/functions-samples#564]
I am implementing firebase functions.  I am getting error while 'firebase serve --only functions'.
Error :
!  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
!  functions: Error from emulator. Error occurred while parsing your function triggers.

TypeError: Cannot read property 'app_shared_secret' of undefined
    at Object.<anonymous> (E:\projects\gatsby-starter-shopify-app-master\functions\helpers\shopify.js:12:54)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\projects\gatsby-starter-shopify-app-master\functions\index.js:12:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

### How to reproduce these conditions

**Sample name or URL where you found the bug**

**Failing Function code used (including require/import commands at the top)**

**Steps to set up and reproduce**

**Sample data pasted or attached as JSON (not an image)**

**Security rules used**

### Debug output

**Errors in the [console logs](https://console.firebase.google.com/project/_/functions/logs?search=&severity=DEBUG)**

**Screenshots**

**Comment by jhuleatt** [comment]
This was an issue in older versions of the `firebase-tools` CLI that has long since been resolved in the CLI.
