### ISSUE TITLE
NextJS hosting example cannot be deployed

### ISSUE THREAD

**Issue by paulkre** [firebase/functions-samples#625]
The example "nextjs-with-firebase-hosting" can not be deployed anymore. Serving locally still works. This might be a bug in [firebase-tools](https://github.com/firebase/firebase-tools) but maybe someone knows a workaround.

### How to reproduce these conditions

1. Clone the repository
1. Go to example "nextjs-with-firebase-hosting"
1. In the package.json change "npm build" to "npm run build" in the "build-next" script
1. Update the dependencies in both the "app" and the "functions" directories (the dependencies are currently severely outdated)
1. `npm run deploy`

### Debug output

```
Error: Could not find a valid build in the '/Users/username/projects/web/functions-samples/nextjs-with-firebase-hosting/next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (/Users/username/projects/web/functions-samples/nextjs-with-firebase-hosting/src/functions/node_modules/next/dist/next-server/server/next-server.js:529:23)
    at new Server (/Users/username/projects/web/functions-samples/nextjs-with-firebase-hosting/src/functions/node_modules/next/dist/next-server/server/next-server.js:48:29)
    at createServer (/Users/username/projects/web/functions-samples/nextjs-with-firebase-hosting/src/functions/node_modules/next/dist/server/next.js:2:133)
    at Object.<anonymous> (/Users/username/projects/web/functions-samples/nextjs-with-firebase-hosting/src/functions/index.js:22:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

### Expected behavior

The deployment is successful.

### Actual behavior

[firebase-tools](https://github.com/firebase/firebase-tools) can not find NextJS's build directory.

Apparently, before deploying, firebase-tools tests the cloud functions by running them. Unfortunately during this process it uses the example's directory as the root working directory when in fact it should be using the "functions" directory as the root.

When you trick the process by using "src/functions/next" as the distDir for NextJS's build, it will upload the example successfully but then fail the tests on the server.

**Comment by maotora** [comment]
Did you run `npm run predeploy` before `npm run deploy`?

**Comment by Kentus** [comment]
I managed to deploy by running `firebase deploy` in src/functions folder.

**Comment by dmurph** [comment]
that's the functions, not the whole app

**Comment by maotora** [comment]
Try to change the distDir configuration to the root of the project like this;

Change next.config.js distDir to 

    distDir: "../../dist/client"

Then fix distDir path in the nextjs server, to point to our built nextjs project from the root of the main `package.json` file.
 
    const app = next({dev, conf: {distDir: 'dist/next'}});

Therefore the `nextjs` build file is in the root of my project.

**Comment by paulkre** [comment]
This does not work because anything located outside the functions directory will not be uploaded to firebase. The local file structure of your project will be different after it has been deployed.

**Comment by Sherange** [comment]
this work for me 
modify src\functions\index.js 


var dev = false
var dir = __dirname
var app = next({ dev, dir, conf: { distDir: 'next' } })

**Comment by jhuleatt** [comment]
(we've removed this sample from this repository in #804)
