### ISSUE TITLE
fcm-notifications

### ISSUE THREAD

**Issue by codeavor-cholo** [firebase/functions-samples#666]
i've followed every instruction listed in the README.md file.
but i can't get to see the users who have sign in to the web app.

is there a missing step i've skip here ? 
i can't get a token for my users after signing in .
or i'll generate it myself ?

There seam to be an error in the console. here it is.

```
subscribe.ts:239 FirebaseError: Messaging: Missing App configuration value: "appId" (messaging/missing-app-config-values).
    at je (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-messaging.js:1:20895)
    at https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-messaging.js:1:38517
    at b.instanceFactory (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-messaging.js:1:38725)
    at P.getOrInitializeService (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-app.js:1:8189)
    at P.getImmediate (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-app.js:1:6457)
    at G._getService (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-app.js:1:13131)
    at G.c.<computed> [as messaging] (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-app.js:1:15846)
    at Object.i [as messaging] (https://testfirebasefunctions-44db3.firebaseapp.com/__/firebase/7.7.0/firebase-app.js:1:15669)
    at Demo.saveToken (https://testfirebasefunctions-44db3.firebaseapp.com/main.js:186:12)
    at Demo.onAuthStateChanged (https://testfirebasefunctions-44db3.firebaseapp.com/main.js:67:10)
```

Thank you in advance for your response. :)

**Comment by jhuleatt** [comment]
Hi @codeavor-cholo, this is a relatively recent change to how Firebase projects are set up. You need to register a web app (instructions [here](https://firebase.google.com/docs/web/setup/#register-app)) to populate the `appId` field of the Firebase config. I'll update the sample instructions to reflect this.
