### ISSUE TITLE
Error in Image moderator

### ISSUE THREAD

**Issue by rajflutter** [firebase/functions-samples#768]
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'Reader' of undefined
    at /Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:28:29
    at /Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:22:26
    at Object.<anonymous> (/Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/protos/protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rva/cloudFunctions/node_modules/@google-cloud/vision/build/src/index.js:52:16)

**Comment by jhuleatt** [comment]
This was an upstream protobuf dependency issue in older `@google-cloud/vision` packages that has been resolved in subsequent releases.
