### ISSUE TITLE
[BUG] Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old.

### ISSUE THREAD

**Issue by bholendraofficial** [firebase/functions-samples#890]
Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old.
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:330:49)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by jhuleatt** [comment]
Closing because this doesn't follow the issue template. @bholendraofficial if you'd like help, please answer the questions in the issue template.
