### ISSUE TITLE
[BUG] in sample: delete-unused-accounts-cron

### ISSUE THREAD

**Issue by polarby** [firebase/functions-samples#953]
### How to reproduce the issue

Deploy function or run the function locally via the shell.

### Debug output

`TypeError: PromisePool is not a constructor`

```
irebase > ⚠  functions: TypeError: PromisePool is not a constructor
    at /Users/*/Documents/*/*-Backend/functions/external/user/user_cleanUp.js:34:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runFunction (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:547:9)
    at async runBackground (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:559:5)
    at async processBackground (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:542:5)
    at async invokeTrigger (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:624:13)
    at async handleMessage (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:717:9)
⚠  Your function was killed because it raised an unhandled error.
```

### Actual behavior

Run function as described in docs.

**Comment by polarby** [comment]
Changed the import to  `const PromisePool = require('es6-promise-pool');`and it worked. Also, make sure to have `es6-promise-pool` installed. (Call `npm i es6-promise-pool`)
